#!/bin/bash

instance_id="YOUR_INSTANCE_ID"

while true; do
    current_hour=$(date +"%H")
    current_minute=$(date +"%M")

    if [ "$current_hour" -eq 17 ] && [ "$current_minute" -eq 0 ]; then
        aws ec2 stop-instances --instance-ids "$instance_id"
        echo "EC2 instance stopped."
    fi

    if [ "$current_hour" -eq 8 ] && [ "$current_minute" -eq 0 ]; then
        aws ec2 start-instances --instance-ids "$instance_id"
        echo "EC2 instance started."
    fi
done
